name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  [ workflow_dispatch, push ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }} - ${{ secrets.GITHUB_TOKEN }}"
    - name: Get the code
      uses: actions/checkout@v3 
    - name: PrintEnv
      run: env
    - name: print git details
      run: echo "${{github.ref}}, ${{github.event_name}}, ${{github.tag}}"
    
